### ISSUE TITLE
TOF minimal example

### ISSUE THREAD

**Issue by Scoeerg** [Sohampaul7/Work#2]
Regarding [TOF minimal example](https://github.com/Sohampaul7/Work/blob/dev/TOF_minimal_example/TOF_minimal_example.ino)

I will be overly pedantic. Not to annoy you, but because you should know what the "ideal" is. "Ideal" is also very subjective, i.e. others might not share my ideas. A great way to get to know what the people around you consider good is to read THEIR code.  

```cpp
#define HEADER 0x59   // Frame starting byte (0x59 for TFMini-S)
#define BUFFER_SIZE 9 // Size of the data packet

// Variables for ToF sensor
uint8_t uart[BUFFER_SIZE];
int16_t dist;
uint8_t chk;
int i;
```

- `uart` is a buffer for the stuff you read from UART connection with size `BUFFERSIZE` - which is a great variable name ;). Name it `buffer` or `uart_buffer` or something. A variable should be as descriptive as possible. 
- therefore `dist` should be `distance` or even `distance_in_millimeter` (or is it centimeter?)
- and `chk` should be `checksum`. 

```cpp
void setup() {
  Serial.begin(9600);       // Debugging output to Serial Monitor
  Serial2.begin(115200);    // TFMini-S is connected to Serial2 (pins 7 and 8)
  
  Serial.println("System Initialized. Starting the loop.");
}
```

```cpp
void loop() {
  // Read distance data from the sensor
  if (Serial2.available()) {
    if (Serial2.read() == HEADER) {
      uart[0] = HEADER;

      if (Serial2.read() == HEADER) {
        uart[1] = HEADER;

        for (i = 2; i < BUFFER_SIZE; i++) {
          uart[i] = Serial2.read();
        }
```

Is the `HEADER`-data transmitted twice, or is this a mistake?  

```cpp
        // Calculate chksum
        chk = uart[0] + uart[1] + uart[2] + uart[3] + uart[4] + uart[5] + uart[6] + uart[7];

        if (uart[8] == (chk & 0xFF)) {
          // Calculate distance
          dist = uart[2] + uart[3] * 256;
        }
      }
    }
  }

```

- if you variable name `chk` is `checksum` you can omit the comment about it entirely, because the software documents itself - anybody can just read the code and understand what's going on. 
- Might be useful to store `0xFF` in a variable and name it `reference_checksum` or similar. 
- catch the `else` and print some form of message e.g. `Checksum was wrong. Check connection?` If a user sees this message a lot, he know the connection is bugged, noisy etc. 

```cpp
  Serial.println(dist);

  delay(5);
}
```

Add some string before the distance, so the user reading the serial data knows what the value means. E.g. 
```cpp
Serial.println("Distance: " + String(dist) + " cm");
delay(5);
}
```

**Comment by Sohampaul7** [comment]
- Fixed the issues.

- The first 2 bytes contain the same header, therefore we are checking twice.
